### ISSUE TITLE
project to image plane

### ISSUE THREAD

**Issue by ASPL-pod** [muhammetbalcilar/DenseDepthMap#1]
Hello, thanks for sharing a useful code. And I have a question in the code

You've coded as follows to remove the point cloud that's not in the camera.
% remove all points behind image plane (approximation)
idx = velo(:,1)<5;
velo(idx,:) = [];
I looked at this code and decided that the point where the camera had less than x=5 coordinates in the point cloud was not visualized.
If my decision is correct, how did you know that x=5 is the point where the camera can't get video?

**Comment by balcilar** [comment]
Actually, it is because of avoiding interference of the points where is behind the camera. Normally we can calculate relative distance from lidar and camera then set that distance there. I recalculated that distance, yeah 5 m is too high, it is not more than 1meter. You can set it 1 for that case, or just calculate the relative distance by the transformation matrix and set that value there.
